name: Heimstaden
baseurl: http://heimstaden.no
fb_appid: 966242223397117
sass:
  sass_dir: assets/css
  style: compressed
excerpt_separator: "<!--more-->"
exclude: ["node_modules", "gulpfile.js", "package.json"]
prose:
  media: 'assets/img'
  metadata:
    _posts:

      - name: "layout"
        field:
          element: "hidden"
          value: "post"

      - name: "date"
        field:
          element: "hidden"
          value: "CURRENT_DATETIME"

      - name: "title"
        field:
          element: "text"
          label: "title"

      - name: "thumbnail"
        field:
          element: "text"
          label: "Thumbnail file name"
          media: "assets/img/tn"

      - name: "description"
        field:
          element: "text"
          label: "En kort beskrivelse innlegg"
